name: Build APK (Dragon Dice)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # Если у вас в CI генерируется иконка/ресурсы — вставьте шаги здесь (необязательно)

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DragonDice-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
